name: my_app_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_feather_icons: ^2.0.0+1
  provider: ^6.0.5
  logger: ^2.0.2+1
  # shared_preferences
  shared_preferences: ^2.2.2
  # url_launcher
  url_launcher: ^6.0.12
  # image_picker
  image_picker: ^1.0.4
  # file_picker
  file_picker: ^6.1.1
  # http
  http: ^1.0.0
  # intl
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  #폴더 내부 모든파일을 사용한다
  assets:
    - images/
